[features]
seeds = false
skip-lint = false
[programs.localnet]
crowndfunding = "UAtcBu9QKREy592cS2EZPgSfmwaP1GCvD2Zo9dNPtYD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
